'''
Proposed Example Idea
- shows all options for each component
  including the inherited properties 
  from kComponent
'''

# imports
import kritter

if __name__ == "__main__":

    # Create Kritter server - server is created before components
    kapp = kritter.Kritter()    

    # Application Styles
    main_style = {"label_width": 3, "control_width": 6}

    # Contents/Components of Application
    header = kritter.Ktext(value="kText Detailed", style=main_style)
    example = kritter.Ktext(
        name="Detailed Text",   # name of object
        id='detailed-id',       # generated by kapp if not given - html id
        value="",               # starting text value
        kapp=kapp,              # ?
        grid=True,              # ?
        layout=None,            # similar to kapp layout - ?
        service=None,           # shared or instance specific
        style=main_style,       # html tag style
        spinner=False,          # allows spinner display 
        disabled=False,         # enable or disable 
        disp=True,              # visible or invisible
    )
    
    # Define Callbacks for Components
    ## kText does not have a callback function

    kapp.layout = [header, example] # define interface layout
    kapp.run()  # Run Server - vizy.local:5000/
